spring:
  profiles: dev
server:
  port: 8090
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignoredServices: '*'
  routes:
    app-externa: /app-externa/**
  #routes:
  #  users:
  #    path: /app/**
  #    serviceId: app-externa
  sensitiveHeaders: Cookie,Set-Cookie

gateway:
  private: app-interna
  