spring:
  profiles: dev
server:
  port: 8090
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  sensitiveHeaders: Cookie,Set-Cookie