spring:
  application:
    name: db-app
  profiles: dev
server:
  port: 9001
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

app:
  saludo: Hola Esteban