spring:
  profiles: dev
server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761
app:
  saludo: Hola Compañeros
---
spring:
  profiles: cert
server:
  port: 9090
app:
  saludo: SkyNEt dominara al Mundo