spring:
  application:
    name: app-interna
  profiles: dev01
server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  saludo: Hola compañeros
---
spring:
  application:
    name: app-externa
  profiles: dev02
server:
  port: 8082
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  saludo: Hola clientes
---
spring:
  profiles: cert
server:
  port: 9090
app:
  saludo: SkyNEt dominara al Mundo