spring:
  application:
    name: turbine-app
  profiles: dev
server:
  port: 1234
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  aggregator:
    clusterConfig: GM
  appConfig: id-types-app